title: Franco's Site
author: Franco Curotto
email: francocurotto@gmail.com
github_username: francocurotto
linkedin_username: francocurotto
theme: minima
header_pages:
    - outreach.md
    - recipes.md
    - caso_sustituto.md
    - jp_lyrics.md
    #minima:
    #social_links:
    #    email: francocurotto@gmail.com
    #    github: francocurotto
    #    linkedin: francocurotto
