title: Franco's Site
author: Franco Curotto
#email: francocurotto@gmail.com
#github_username: francocurotto
theme: minima
header_pages:
    - outreach.md
    - recipes.md
    - caso_sustituto.md
    - jp_lyrics.md
minima:
    social_links:
        - { platform: email,   user_url: "mailto:francocurotto@gmail.com" }
        - { platform: github,  user_url: "https://github.com/francocurotto" }
        - { platform: linkedin, user_url: "https://linkedin/in/francocurotto" }
